IceCream/IceCreamClient/Areas/Admin/Controllers/BookController.cs
using IceCreamClient.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace IceCreamClient.Areas.Admin.Controllers
{
    [Area("Admin")]//thêm route /admin/book cho trang admin
    public class BookController : Controller
    {
        const string BASE_URL = "http://localhost:47255";
        IHttpClientFactory factory;
        IWebHostEnvironment env; //upload image

        public BookController(IHttpClientFactory factory, IWebHostEnvironment env)
        {
            this.factory = factory;
            this.env = env;
        }

        //view book
        public async Task<IActionResult> ShowBooks()
        {
            //check admin login
            if (HttpContext.Session.GetString("adname") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpClient client = factory.CreateClient();//tạo và nhận data
            var result = await client.GetAsync(BASE_URL + "/api/book");
            //cần kiểm tra return code => để xem có dữ liệu hay ko? :tự làm
            var data = await result.Content.ReadAsStringAsync();
            var books = JsonConvert.DeserializeObject<List<BookIceCream>>(data);

            client.Dispose();
            return View(books);//trả về view obj book hiện tại để hiển thị thông tin book, ko có sẽ bị lỗi null model khi show list bên ShowEmps.cshtml
        }
        //end view book

        //create
        public async Task<IActionResult> CreateBook()
        {
            //display dropdown list category in create
            HttpClient client = factory.CreateClient();//tạo và nhận data
            var resultCate = await client.GetStringAsync(BASE_URL + "/api/category");
            var cate = JsonConvert.DeserializeObject<List<Category>>(resultCate);
            TempData["ListCate"] = cate;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBook(BookIceCream book, IFormFile Image)
        {
            //check admin login
            if (HttpContext.Session.GetString("adname") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpClient client = factory.CreateClient();//tạo và nhận data

            if (ModelState.IsValid)//validate
            {
                if (Image != null)
                    {
                    //ADD IMAGE
                    //upload file
                    string filename = Image.FileName;

                    //auto check and create folder
                    var imagesFolder = Path.Combine(env.WebRootPath, "images/book");
                    if (!Directory.Exists(imagesFolder))
                    {
                        Directory.CreateDirectory(imagesFolder);
                    }

                    var filePath = Path.Combine(imagesFolder, filename);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await Image.CopyToAsync(stream);
                    book.Image = filename;
                }

                //create book
                var bookJson = JsonConvert.SerializeObject(book);
                var stringContent = new StringContent(bookJson, Encoding.UTF8, "application/json");
                var result = await client.PostAsync(BASE_URL + "/api/book/", stringContent);
                client.Dispose();
                return RedirectToAction("ShowBooks");
            }
            //display dropdown list category
            //fix lỗi null categories khi return view() validate field bên CreateBook
            var resultCate = await client.GetStringAsync(BASE_URL + "/api/category");
            var cate = JsonConvert.DeserializeObject<List<Category>>(resultCate);
            TempData["ListCate"] = cate;
            //end

            return View();
        }
        //end create

        //hàm GetBook để lấy data của obj book từ db theo id
        public async Task<BookIceCream> GetBook(int id)
        {
            HttpClient client = factory.CreateClient();
            //chuyển đối tượng customer thành chuỗi json để truyền đi
            var response = await client.GetStringAsync(BASE_URL + $"/api/book/{id}");
            var book = JsonConvert.DeserializeObject<BookIceCream>(response);
            client.Dispose();
            return book;
        }
        //end

        //Update book
        public async Task<IActionResult> UpdateBook(int bookId) // bookId phải giống với link bookId = item.BookId bên ShowBooks.cshtml
        {
            //check admin login
            if (HttpContext.Session.GetString("adname") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpClient client = factory.CreateClient();

            var response = await client.GetStringAsync(BASE_URL + $"/api/book/{bookId}");
            var book = JsonConvert.DeserializeObject<BookIceCream>(response);

            //dropdown list category
            var resultCate = await client.GetStringAsync(BASE_URL + "/api/category");
            var cate = JsonConvert.DeserializeObject<List<Category>>(resultCate);
            TempData["ListCate"] = cate;
            //end
            
            client.Dispose();
            return View(book);//trả về view obj customer hiện tại để hiển thị thông tin sau edit, ko có sẽ bị lỗi null model khi show list bên showEmps.cshtml
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBook(int bookId, BookIceCream book, IFormFile Image)
        {
            HttpClient client = factory.CreateClient();

            //display dropdown list category
            //fix lỗi null categories khi dùng return view() validate field bên UpdateBook
            var resultCate = await client.GetStringAsync(BASE_URL + "/api/category");
            var cate = JsonConvert.DeserializeObject<List<Category>>(resultCate);
            TempData["ListCate"] = cate;
            //end

            if (ModelState.IsValid)//validate
            {
                if (Image != null) //checking if upload new image
                {
                    //ADD IMAGE
                    //upload file
                    string filename = Image.FileName;

                    //auto check and create folder
                    var imagesFolder = Path.Combine(env.WebRootPath, "images/book");
                    if (!Directory.Exists(imagesFolder))
                    {
                        Directory.CreateDirectory(imagesFolder);
                    }

                    var filePath = Path.Combine(imagesFolder, filename);
                    var stream = new FileStream(filePath, FileMode.Create);
                    await Image.CopyToAsync(stream);
                    book.Image = filename;
                }
                else//no upload new image
                {
                    var oldImage = await GetBook(bookId);
                    book.Image = oldImage.Image;
                }
                var json = JsonConvert.SerializeObject(book);
                var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
                var result = await client.PutAsync(BASE_URL + "/api/book", stringContent);

                if (result.IsSuccessStatusCode)
                {
                    ViewData["success"] = "Updated Book successful.";
                }
                client.Dispose();
                return View(book);
            }
            return View(book);//trả về view obj customer hiện tại để hiển thị thông tin sau edit, ko có sẽ bị lỗi null model khi update failed
        }
        //END UPDATE

        //DETAILS BOOK
        public async Task<IActionResult> BookDetails(int bookId) // bookId phải giống với link bookId = item.BookId bên ShowBooks.cshtml
        {
            //check admin login
            if (HttpContext.Session.GetString("adname") == null)
            {
                return RedirectToAction("Login", "Home");
            }

            HttpClient client = factory.CreateClient();
            var response = await client.GetStringAsync(BASE_URL + $"/api/book/{bookId}");
            var book = JsonConvert.DeserializeObject<BookIceCream>(response);

            //display dropdown list category
            //fix lỗi null categories khi dùng return view() validate field bên UpdateBook
            var resultCate = await client.GetStringAsync(BASE_URL + "/api/category");
            var cate = JsonConvert.DeserializeObject<List<Category>>(resultCate);
            TempData["ListCate"] = cate;
            //end

            client.Dispose();
            return View(book);
        }

        //update status active
        public async Task<IActionResult> UpdateStatus(int bookId, bool status)
        {
            HttpClient client = factory.CreateClient();
            var stringContent = new StringContent("", Encoding.UTF8, "application/json");
            var result = await client.PostAsync(BASE_URL + $"/api/book/status/{bookId}/{status}", stringContent);
            if (result.IsSuccessStatusCode)
            {
                ViewData["success"] = "Updated Book successful.";
            }
            return RedirectToAction("ShowBooks");
        }
        //end update status
    }
}

IceCream/IceCreamClient/Controllers/CartController.cs
using IceCreamClient.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace IceCreamClient.Controllers
{
    public class CartController : Controller
    {
        const string API_URl = "http://localhost/IceCreamApi";
        IHttpClientFactory _factory;

        public CartController(IHttpClientFactory factory)
        {
            _factory = factory;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int id, int quantity, string button)
        {
            HttpClient client = _factory.CreateClient();
            var result = await client.GetAsync(API_URl + $"/api/Book/{id}");
            var data = await result.Content.ReadAsStringAsync();
            var book = JsonConvert.DeserializeObject<BookIceCream>(data);
            client.Dispose();

            string json = HttpContext.Session.GetString("cart");
            List<Cart> listCart = new List<Cart>();

            if (json != null)
            {
                JArray jsonResponse = JArray.Parse(json);
                foreach (var item in jsonResponse)
                {
                    JObject cartResult = (JObject)item;
                    listCart.Add(JsonConvert.DeserializeObject<Cart>(cartResult.ToString()));
                }
            }

            if (button == "delete")
            {
                int delete_index = -1;
                foreach (Cart item in listCart)
                {
                    delete_index++;
                    if (item.BookIceCream.BookId == id)
                    {
                        break;
                    }
                }

                listCart.RemoveAt(delete_index);
            }
            else
            {
                Cart cart = listCart.Where(i => i.BookIceCream.BookId.Equals(id)).FirstOrDefault();

                if (listCart.Count > 0 && cart != null)
                {
                    cart.Quantity = quantity;
                }
                else
                {
                    Cart newProduct = new Cart { BookIceCream = book, Quantity = quantity, Price = book.Price };
                    listCart.Add(newProduct);
                }
            }

            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(listCart));
            return Redirect(Request.Headers["Referer"].ToString());
            //return RedirectToAction("Index", "Home");
        }
       
    }
}

IceCream/IceCreamClient/Views/Book/BookDetails.cshtml
@model IceCreamClient.Models.BookIceCream
@{
    ViewData["Title"] = "BookDetails";
    //show IEnumerable model relatedbook in detail page model
    IEnumerable<BookIceCream> relatedBook = ViewData["RelateBook"] as IEnumerable<BookIceCream>;
}

<!--Page Title-->
<section class="page-title centred" style="background-image: url('/assets/images/background/page-title.jpg');">
    <div class="auto-container">
        <div class="content-box">
            <div class="title">
                <h1>Shop Book Details</h1>
            </div>
            <ul class="bread-crumb clearfix">
                <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                <li>Details</li>
            </ul>
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- single-product -->
<section class="single-product">
    <div class="product-details-content" style="background-image: url('/images/book/@Model.Image')">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-6 col-md-12 col-sm-12 image-column">
                    <div class="bxslider">
                        @*Error bxslider*@
                        <div class="slider-content">
                            <div class="slider-pager">
                                <ul class="thumb-box">
                                    <li>
                                        @* hiển thị image*@
                                        @if (Model.Image != null)
                                        {
                                            <a class="active" data-slide-index="0" href="#">
                                                <figure>
                                                    <img src="~/images/book/@Model.Image" alt="picture">
                                                </figure>
                                            </a>
                                        }
                                    </li>
                                </ul>
                            </div>
                            <div class="product-image">
                                @if (Model.Image != null)
                                {
                                    <figure class="image">
                                        <a href="~/images/book/@Model.Image" class="lightbox-image" data-fancybox="gallery">
                                            <img src="~/images/book/@Model.Image" alt="picture">
                                        </a>
                                    </figure>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 content-column">
                    <div class="product-details">
                        <h2>@Model.Title</h2>
                        <h3>$@Model.Price</h3>
                        <div class="customer-rating clearfix">
                            <ul class="rating pull-left">
                                <li><i class="icon-Star"></i></li>
                                <li><i class="icon-Star"></i></li>
                                <li><i class="icon-Star"></i></li>
                                <li><i class="icon-Star"></i></li>
                                <li><i class="icon-Star"></i></li>
                            </ul>
                        </div>
                        <div class="addto-cart-box">
                            @* Add to cart *@
                            <form asp-action="AddToCart" asp-controller="Cart" method="get">
                                <ul class="clearfix">
                                    <li><input type="hidden" name="id" value="@Model.BookId"></li>
                                    <li><input type="number" min="1" max="1000" name="quantity" value="1" placeholder="1" style="width:fit-content;height:50px;"></li>
                                    <li><button type="submit" class="theme-btn-two" value="add">Add to cart</button></li>
                                </ul>
                            </form>
                        </div>
                        <div class="other-links">
                            <ul class="category list">
                                <li>Category:</li>
                                <li>Ice Cream</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="product-discription">
        <div class="auto-container">
            <div class="tabs-box">
                <div class="tab-btn-box">
                    <ul class="tab-btns tab-buttons clearfix">
                        <li class="tab-btn active-btn" data-tab="#tab-1">Description</li>
                    </ul>
                </div>
                <div class="tabs-content">
                    <div class="tab active-tab" id="tab-1">
                        <div class="content-box">
                            @* Description: Display text decoding html entity*@
                            @Html.Raw(Model.Description)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="related-product" style="background-image: url(/assets/images/background/single-shop-1.jpg);">
        <div class="auto-container">
            <div class="top-title centred">
                <h2>Related Products</h2>
            </div>
            <div class="row clearfix">
                @foreach (var item in relatedBook)
                {
                    <div class="col-lg-3 col-md-6 col-sm-12 shop-block">
                        <div class="shop-block-one">
                            <div class="inner-box" style="min-height:500px;">
                                <figure class="image-box">
                                    <img src="~/images/book/@Html.Raw(item.Image)" alt="No image" style="height:270px; width:100%">
                                </figure>
                                <div class="lower-content">
                                    <span class="price-box">$@item.Price</span>
                                    <h3><a href="@Url.Action("BookDetails", "Book", new { bookId = item.BookId})">@Html.Raw(item.Title)</a></h3>
                                    <ul class="rating clearfix">
                                        <li><i class="icon-Star"></i></li>
                                        <li><i class="icon-Star"></i></li>
                                        <li><i class="icon-Star"></i></li>
                                        <li><i class="icon-Star"></i></li>
                                        <li><i class="icon-Star"></i></li>
                                    </ul>
                                    @*add to Cart *@
                                    <div class="cart-btn">
                                        <form asp-action="AddToCart" asp-controller="Cart" method="get">
                                            <input type="hidden" name="id" value="@item.BookId">
                                            <input type="hidden" name="quantity" value="1">
                                            <button type="submit" class="theme-btn-two" value="add">Add to cart</button>
                                        </form>

                                        @*<a href="shop-details.html" class="theme-btn-two">Add to cart</a>*@
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
<!-- single-product end -->

IceCream/IceCreamClient/Views/Book/ShowBookByCategory.cshtml
@model IEnumerable<IceCreamClient.Models.BookIceCream>

@{
    ViewData["Title"] = "ShowBookByCategory";
    //show IEnumerable model categories in show list page model
    IEnumerable<Category> categories = TempData["Categories"] as IEnumerable<Category>;
    //show IEnumerable model relatedbook Feature Book in showbooks page model
    IEnumerable<BookIceCream> relatedBook = ViewData["RelateBook"] as IEnumerable<BookIceCream>;
}

<!--Page Title-->
<section class="page-title centred" style="background-image: url(assets/images/background/page-title.jpg);">
    <div class="auto-container">
        <div class="content-box">
            <div class="title">
                <h1>Book</h1>
            </div>
            <ul class="bread-crumb clearfix">
                <li><a asp-action="Index" asp-controller="Home">Home</a></li>
                <li>Show Book</li>
            </ul>
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- shop-page-section -->
<section class="shop-page-section shop-page-1" style="background-image: url('/assets/images/background/shop-1.jpg');">
    <div class="auto-container">
        <div class="row clearfix">
            <div class="col-lg-3 col-md-12 col-sm-12 sidebar-side">
                <div class="shop-sidebar default-sidebar">
                    <div class="sidebar-widget sidebar-search">
                        <form asp-action="ShowBooks" class="search-form">
                            <div class="form-group">
                                <input type="search" name="title" placeholder="Search..." required="">
                                @*pass value page = 1 to showbooks(title, page) to active page 1 when search*@
                                <input type="hidden" name="page" value="1" />
                                <button type="submit"><i class="icon-Search"></i></button>
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-widget sidebar-categories">
                        <div class="widget-title">
                            <h3>Shop by Categories</h3>
                        </div>
                        <div class="widget-content">
                            <ul class="categories-list clearfix">
                                <li><a href="@Url.ActionLink("ShowBooks", "Book", new {page = 1})">All</a></li>
                                @foreach (var item in categories)
                                {
                                    <li><a href="@Url.ActionLink("ShowBookByCategory", "Book", new { CatId = item.CatId, page = 1 })">@item.Name</a></li>
                                }
                            </ul>
                        </div>
                    </div>
                    @* remove price-filter to fix error preloader stuck *@
                <div class="sidebar-widget post-widget">
                    <div class="widget-title">
                        <h3>Newest Books</h3>
                    </div>
                    <div class="post-inner">
                        @foreach (var item in relatedBook)
                        {
                            <div class="post">
                                <figure class="image-box">
                                    <a href="@Url.Action("BookDetails", "Book", new { bookId = item.BookId})">
                                        <img src="~/images/book/@item.Image" alt="" style="height:100%; width:100%">
                                    </a>
                                </figure>
                                <h5><a href="@Url.Action("BookDetails", "Book", new { bookId = item.BookId})">@item.Title</a></h5>
                                <p>$@item.Price</p>
                            </div>
                        }
                    </div>
                </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-12 col-sm-12 content-side">
                <div class="our-shop">
                    <div class="item-shorting clearfix">
                        <div class="left-column pull-left clearfix">
                            <div class="text"><p>Showing 1–6 Book of Results</p></div>
                        </div>
                        <div class="right-column pull-right clearfix">
                            <div class="short-box clearfix">

                            </div>
                            <div class="menu-box">
                                <a href="#"><i class="icon-Menu"></i></a>
                            </div>
                        </div>
                    </div>

                    @if (Model != null && Model.Count() > 0) // nếu search tìm thấy record trong db thì hiển thị
                    {
                        <div class="row clearfix">
                            @* ShowBooks *@
                            @foreach (var item in Model)
                            {
                                @if (item.Active == true)
                                {
                                    //show all
                                    <div class="col-lg-4 col-md-6 col-sm-12 shop-block">
                                        <div class="shop-block-one">
                                            <div class="inner-box" style="min-height:500px;">
                                                <figure class="image-box">
                                                    @if (item.Image != null)
                                                    {
                                                        <img src="~/images/book/@item.Image" alt="no image" style="height:270px; width:100%" />
                                                    }
                                                    else
                                                    {
                                                        @: No Image
                                                    }
                                                </figure>
                                                <div class="lower-content">
                                                    <span class="price-box">$@item.Price</span>
                                                    <h3 style="min-height:100px;">
                                                        <a href="@Url.ActionLink("BookDetails", "Book", new { bookId = item.BookId })">@item.Title</a>
                                                    </h3>
                                                    <ul class="rating clearfix">
                                                        <li><i class="icon-Star"></i></li>
                                                        <li><i class="icon-Star"></i></li>
                                                        <li><i class="icon-Star"></i></li>
                                                        <li><i class="icon-Star"></i></li>
                                                        <li><i class="icon-Star"></i></li>
                                                    </ul>
                                                    @* Add to cart *@
                                                    <div class="cart-btn">
                                                        <form asp-action="AddToCart" asp-controller="Cart" method="get">
                                                            <input type="hidden" name="id" value="@item.BookId">
                                                            <input type="hidden" name="quantity" value="1">
                                                            <button type="submit" class="theme-btn-two" value="add">Add to cart</button>
                                                        </form>

                                                        @*<a href="shop-details.html" class="theme-btn-two">Add to cart</a>*@
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                            @* End ShowBooks *@
                        </div>
                    }
                    else
                    {
                        <div class="row clearfix">
                            <h5>No keyword for search match name of book</h5>
                        </div>
                    }
                    @* end search if *@

                    <div class="pagination-wrapper centred">
                        <ul class="pagination">
                            @* PAGINATION BOOKS WITH VIEW ALL *@
                            @{
                                int currentPage = Convert.ToInt32(TempData["CurrentPage"]);
                                int totalPage = Convert.ToInt32(TempData["TotalPage"]);
                                if (currentPage != 1)
                                {
                                    <li><a asp-action="ShowBookByCategory" asp-controller="Book" asp-route-page="@(Convert.ToInt32(currentPage - 1))">Prev</a></li>
                                }
                                else
                                {
                                    <li><a href="javascript:void(0)">Prev</a></li>
                                }

                                for (int i = 1; i <= totalPage; i++)
                                {
                                    if (currentPage == i)
                                    {
                                        <li><a href="javascript:void(0)" class="active">@i</a></li>
                                    }
                                    else
                                    {
                                        <li><a asp-action="ShowBookByCategory" asp-controller="Book" asp-route-CatId="@TempData["CategoryID"]" asp-route-page="@i">@i</a></li>
                                    }
                                }

                                if (currentPage < totalPage)
                                {
                                    <li><a asp-action="ShowBookByCategory" asp-controller="Book" asp-route-CatId="@TempData["CategoryID"]" asp-route-page="@(Convert.ToInt32(currentPage + 1))">Next</a></li>
                                }

                                if (currentPage == totalPage)
                                {
                                    <li><a href="javascript:void(0)">Next</a></li>
                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>